### PR TITLE
Updating workshop

### PR DESCRIPTION
**Pull request by davmayd**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tonynv** [comment]
👍🏽

**Comment by davmayd** [comment]
Thanks Shivansh. I have added curl commands to automatically append the workshop file content.

**Comment by russomi** [comment]
👋🏼 @tonynv Happy Holidays!  🙏🏼

**Comment by tonynv** [comment]
> 👋🏼 @tonynv Happy Holidays! 🙏🏼

Same to you 🥳🎉🎄

**Comment by sshvans** [comment]
Outdated.

**Pull request closed without merging**
